from pathlib import Path
from html import escape
root=Path(__file__).parent
projects=[
('radar','Doprava','Radar na Zámostku','Příprava je téměř u konce. Nyní čekáme na vyjádření dotčených orgánů. Chceme navázat na dosavadní práci a projekt dotáhnout do konce.',None),
('skolka','Veřejný prostor','Okolí školky','Budeme pokračovat ve zvelebování prostoru kolem mateřské školy: navazující úpravy včetně obrubníků, výsadba zeleně a úpravy parkovacích míst.',None),
('cyklostezka','Propojení obcí','Cyklostezka Marefy–Křižanovice','Dokončujeme úkony nutné pro podání žádosti o stavební povolení. Chceme dovést přípravu k realizaci a využít odpovídající dotační podporu.','cyklostezka'),
('chodniky','Pohyb po obci','Opravy a nové chodníky','Budeme pokračovat v postupných opravách. Zpracované projekty máme na opravu chodníku od přejezdu k mostu a na nový chodník od čp. 86 po přejezd.',None),
('potok','Krajina a voda','Revitalizace Křižanovického potoka','Pokračujeme v jednáních s Lesy ČR, s. p., o revitalizaci a zpracování projektu. Jde o dlouhodobý úkol. Ve svém úsilí nepolevíme a chceme přípravu posouvat dál.',None),
('lavka','Konkrétní projekt','Nová lávka přes Litavu','Čekáme na dokončení projektu. Následovat má podání žádosti o stavební povolení. Předpokládaná realizace: do konce roku 2027.','lavka'),
('spolky','Život v obci','Podpora spolků','Budeme pokračovat v podpoře našich spolků a jejich aktivit finanční, materiální i praktickou pomocí. Všechny spolky v Křižanovicích budou mít naši podporu i v dalších letech.',None),
('pila','Podoba obce','Areál bývalé pily','V mezích zákona využijeme územní plán i vyjádření obce ve stavebním řízení. Případná nová zástavba má respektovat ráz obce a mít vyřešenou dopravu i sítě.',None),
('statek','Dlouhodobý problém','Areál bývalého statku','Jsme připraveni být aktivním partnerem při řešení situace v areálu bývalého statku. Budeme zasílat písemné podněty příslušným úřadům a důsledně sledovat, jak byly vyřízeny.',None),
('tunky','Krajina a voda','Soustava tůněk','Jeden projekt, tři užitky: zpomalit přívalovou vodu, zadržet vodu v krajině v suchých měsících a vytvořit místo na procházku v dostupné vzdálenosti. Počítáme s využitím dotací.','tunky'),
('park','Veřejný prostor','Park a okolí školy','Revitalizujeme park a upravíme bezprostřední okolí školy. Chceme vytvořit další místo pro odpočinek a setkávání nejen dětí.','park'),
('hrani','Volný čas','Venkovní herní a volnočasové prvky','Vytvoříme nová místa pro herní a volnočasové aktivity. Počítáme například s kuželkami, tabulí na kreslení a dalšími prvky podle návrhů občanů.',None),
('energie','Energetický audit','Snížení nákladů na energie','Zajistíme profesionální prověření obecních budov a veřejného osvětlení ve spolupráci s Jihomoravskou energetickou agenturou JIMEG. Přijmeme doporučená opatření vedoucí ke snížení spotřeby energií.',None)]
names=[('Marie Rozehnalová',63,2),('Ing. Martin Cabala',41,1),('Bc. Petr Přerovský',52,3),('Ing. Pavel Šrankota',40,6),('Jiří Šafařík',39,4),('Mgr. Juraj Greš',42,5),('Petr Hedbávný',48,9),('Mgr. Renata Svobodová',41,7),('Ing. Vojtěch Prachař',32,8)]
def cards(items):
 return ''.join(f'''<article class="project" id="{id}">{f'<figure><img src="assets/{img}.webp" alt="Návrhová vizualizace: {title}" loading="lazy" width="800" height="450"><figcaption>Návrhová vizualizace · ne finální podoba projektu</figcaption></figure>' if img else ''}<div class="project-body"><p class="eyebrow">{category}</p><h3>{title}</h3><p>{desc}</p></div></article>''' for id,category,title,desc,img in items)
def overview(items): return '<ul>'+''.join(f'<li><a href="#{p[0]}">{p[2]} <span aria-hidden="true">↗</span></a></li>' for p in items)+'</ul>'
html='''<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>PRO KŘIŽANOVICE 2026 — Volební program</title><meta name="description" content="Volební program 2026–2030 sdružení nezávislých kandidátů PRO KŘIŽANOVICE 2026. Projekty, kandidáti a informace k volbám."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='5' fill='%23132149'/%3E%3Ctext x='8' y='24' font-family='Arial' font-size='24' font-weight='bold' fill='%23ffdf37'%3EP%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><meta property="og:type" content="website"><meta property="og:locale" content="cs_CZ"><meta property="og:site_name" content="PRO KŘIŽANOVICE 2026"><meta property="og:title" content="PRO KŘIŽANOVICE 2026 — Volební program"><meta property="og:description" content="Volební program 2026–2030, naše projekty, kandidáti a informace k volbám v Křižanovicích."><meta property="og:url" content="https://prokrizanovice.cz/"><meta property="og:image" content="https://prokrizanovice.cz/assets/facebook-share-logo.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="Celé logo PRO KŘIŽANOVICE 2026 — Sdružení nezávislých kandidátů na bílém pozadí"></head><body><a class="skip" href="#program">Přejít na program</a>
<header><a class="brand" href="#uvod" aria-label="PRO Křižanovice 2026, úvod"><img class="header-logo" src="assets/web-logo-header.webp" alt="PRO KŘIŽANOVICE 2026 — sdružení nezávislých kandidátů" width="1080" height="360"></a><nav aria-label="Hlavní navigace"><a href="#program">Program</a><a href="#kandidati">Kandidáti</a><a href="#jak-volit">Jak volit</a></nav></header>
<main><section class="hero" id="uvod"><img class="facebook-cover" src="assets/uvodni-cover-final.png" alt="Panorama Křižanovic s kostelem a modrožlutým motivem" width="2055" height="765" fetchpriority="high"><div class="hero-inner"><h1 class="eyebrow">Volební program 2026–2030</h1><div class="actions"><a class="button yellow" href="#program">Prohlédnout program <span aria-hidden="true">↓</span></a><a class="hero-link" href="#kandidati">Naši kandidáti ↗</a></div><div class="hero-bottom"><span>Volby do zastupitelstva obce<br><strong>9. a 10. října 2026</strong></span></div></div></section>
<section class="section" id="program"><div class="section-heading"><p class="eyebrow">Náš přístup</p><h2>Navázat na rozpracované.<br>Připravit nové.</h2><p>Bez velkých gest. S konkrétními kroky.</p></div><div class="overview"><div><span class="section-num">01</span><h3>Pokračujeme</h3><p>Dotáhneme rozpracované projekty a navážeme na to, co v obci dává smysl.</p>OVERVIEW1</div><div><span class="section-num">02</span><h3>Nové výzvy</h3><p>Nové záměry připravíme s využitím dostupných dotací a s respektem k charakteru obce.</p>OVERVIEW2</div></div></section>
<section class="projects-section" id="pokracujeme"><div class="section"><div class="project-heading"><div><p class="eyebrow">01 / Rozpracované projekty</p><h2>Pokračujeme.</h2></div><p>Rozdělané věci dotáhneme.</p></div><div class="project-grid">CARDS1</div></div></section>
<section class="section" id="nove-vyzvy"><div class="project-heading"><div><p class="eyebrow">02 / Další výzvy a cíle</p><h2>Nové věci rozjedeme.</h2></div><p>S respektem k obci.<br>S využitím dostupných dotací.</p></div><div class="project-grid">CARDS2</div></section>
<section class="principle"><div class="section"><p class="eyebrow">Společný základ našich projektů</p><h2>S rozmyslem.<br>S využitím dotací.<br><span>S respektem k obci.</span></h2><p>Křižanovice mají zůstat místem, které má svůj charakter a kde se dobře žije.</p></div></section>
<section class="section" id="kandidati"><div class="section-heading"><p class="eyebrow">Lidé za programem</p><h2>Naši kandidáti.</h2><p>Všichni kandidáti jsou bez politické příslušnosti.</p></div><ol class="candidates">CANDIDATES</ol></section>
<section class="section vote" id="jak-volit"><div><p class="eyebrow">Volby do zastupitelstva obce</p><h2>Přijďte volit.</h2><p class="date">9. a 10. října 2026</p><div class="times"><div><span>Pátek 9. října</span><strong>14–22 h</strong></div><div><span>Sobota 10. října</span><strong>8–14 h</strong></div></div><p>O Křižanovicích rozhodnou ti, kdo přijdou.</p></div><div class="ballot"><p class="eyebrow">Jak volit</p><h3>Chcete podpořit celou naši kandidátku?</h3><p>Označte křížkem pouze velký čtverec u názvu našeho sdružení.</p><div class="ballot-example"><span aria-hidden="true">×</span><strong>SDRUŽENÍ NEZÁVISLÝCH KANDIDÁTŮ<br>PRO KŘIŽANOVICE 2026</strong></div><p>Křížky u kandidátů jiných sdružení nebo stran přidělí část hlasů i jim. Počet hlasů odpovídá počtu volených zastupitelů.</p><details><summary>Další možnosti hlasování</summary><p>Podle volebního letáku se v obci volí 9 zastupitelů, každý volič tedy má 9 hlasů.</p><p><strong>Jednotliví kandidáti:</strong> Křížkujte malé čtverečky u jmen kandidátů z různých kandidátek. Nesmíte označit více kandidátů, než je počet volených zastupitelů.</p><p><strong>Kombinace:</strong> Označte jednu stranu a jednotlivé kandidáty z jiných stran. Hlasy získají nejprve jednotlivě označení kandidáti; zbývající hlasy získají kandidáti označené strany podle pořadí na volebním lístku.</p></details></div></section></main>
<footer><a href="#uvod">Zpět nahoru ↑</a></footer></body></html>'''
for key,value in [('OVERVIEW1',overview(projects[:7])),('OVERVIEW2',overview(projects[7:])),('CARDS1',cards(projects[:7])),('CARDS2',cards(projects[7:])),('CANDIDATES',''.join(f'<li><div class="portrait"><img src="assets/kandidat-{img}-uniform.webp" alt="{name}" loading="lazy" width="400" height="480"><span>{i}</span></div><h3>{name}</h3><p>{age} let</p></li>' for i,(name,age,img) in enumerate(names,1)))]: html=html.replace(key,value)
(root/'index.html').write_text(html)
